### ISSUE TITLE
Added source from patch to trunk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dgoyal1504/ethernetip4j#1]
```
Now supports more complex tags using the "." notation from the user side hiding 
the protocol specific delimiters.


```

Original issue reported on code.google.com by `sewallin...@gmail.com` on 14 Oct 2012 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
Thanks for accepting my patch!  I will test this new version and let you know 
if I see any issues.
```

Original comment by `travisbe...@gmail.com` on 4 Dec 2012 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
I would Read data from micrologix 1100 by SimpleLogixCommunicator.read(tagName) 
,but I do not know how I know tagname for Counter (C5:0.ACC)
```

Original comment by `kabdel4...@gmail.com` on 28 Oct 2013 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
My patch for handling complex tag names has been working well for us on 2 
production systems since April of 2013.
```

Original comment by `travisbe...@gmail.com` on 6 Feb 2014 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Hi am trying to communicate 1400 with java,, 

My connection s getting success & while reading N7:0 ,getting the exception 
follows


Exception in thread "main" java.lang.NullPointerException
    at com.emergys.plc.Rockwell.ReadWrite.ControlLogixConnector.receiveData(ControlLogixConnector.java:176)
    at com.emergys.plc.Rockwell.ReadWrite.JavaMainController.main(JavaMainController.java:35)



This s my code for reading n7:0


System.out.println("Coming inside the main Class....");
         EthernetIpBufferUtil messageBuffer = null;
         String host = "192.168.1.5";
         int portNo  = 80;
         ControlLogixConnector c = new ControlLogixConnector(host,portNo);
         c.connect();
         System.out.println("Connection is OK..Reading started..");
         String[] tagnames = {"N7:0"};
         SimpleLogixCommunicator sComm = new SimpleLogixCommunicator(host, portNo);
         ByteBuffer buffer = null;

         /*CipMessageRouterRequest.fillBuffer(80, "TEST_INT_READ",(Object)0 , 1, messageBuffer);*/
         //CipMessageRouterRequest.getRequestTagName(buffer, "N7:0");

    Object[] taglistValue = sComm.read(tagnames);
    for ( int i = 0 ; i < taglistValue.length ; i++)
       {
        System.out.println("Tag value List is : /n  " + taglistValue[i]);
       }



```

Original comment by `randy.ne...@gmail.com` on 8 Sep 2014 at 5:50
